name: poke_dapp_2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  domain:
    path: ./domain
  flutter_riverpod: ^2.4.9
  go_router: ^14.1.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  logger: ^2.0.2+1
  riverpod: ^2.4.9
  rxdart: ^0.27.7
  json_serializable: ^6.7.1
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  flutter_svg: ^2.0.10+1
  dio: ^5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  main_locale: pt_BR